apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: <domain>
  namespace: default
spec:
  secretName: <domain>-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: <domain>
  dnsNames:
    - <domain>
